### PR TITLE
Create Bounce.glsl

### PR DESCRIPTION
**Pull request by adrian-purser**

### CODE REVIEW

**Comment by gre** [comment]
thanks for your contribution.

ideally we should avoid if() else() in GLSL and privilege a combination of `mix` and `step`.

if you don't see how, and if you don't mind i'll modify your PR to refactor this a bit

**Comment by adrian-purser** [comment]
Hi,

That would be great. I haven't done much GLSL so I'd be interested in
learning from your changes.

Many Thanks,

Kind Regards,

Adrian

**Comment by gre** [comment]
I've updated, it is the same transition but don't have any if-s

instead use combination of these 2:

screen shot 2017-11-11 at 08 48 20
screen shot 2017-11-11 at 08 48 26

I also have externalize some consts as uniforms so they potentially can be customized.

I also have added a smooth transition on the shadow at the end, so the if(progress=1.0) is not required.

**Comment by Md-Mahfuzur-Rahman** [comment]
Hello @gre and @adrian-purser ,
I used this shader code in iPhone but the bounce going up instead of down. Which value should I change to achieve this. Thanks in advance.

**Comment by gre** [comment]
that may be related to the "Y FLIP" config you are in.
it depends on the implementation that "runs" this shader essentially.

and typically in webgl we can do **gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);** but it's specific to WebGL.

I'm not sure what's easiest for your case, but essentially you can try to change the image lookup functions and also change the vertex position mapping to make it work.

https://github.com/gl-transitions/gl-transitions#contextual-functions should allows it.

**Comment by succulen-plants** [comment]
I directly used the following command line: ffmpeg -i 123714.mp4 -i 471996.mp4 -filter_complex "gltransition=source=./transitions/Bounce.glsl" -y Bounce.mp4; It doesn't properly display the second video and there is no bounce effect.

**Pull request merged**
