### PR TITLE
Add perlin.glsl

### PR DESCRIPTION
**Pull request by Rich-Harris**

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Hah, looks like I got something backwards... hang on, will update the PR!

**Comment by gre** [comment]
aha it's funny the validator didn't see the first result to be invalid (it checks color value at some point, not 100% perfect^^)

anyway, woo that's an awesome transition

**Comment by gre** [comment]
I don't know if possible but it would be neat if we could give another parameter which is a seed , so you can generate unique effects. do you think it's possible?

**Comment by Rich-Harris** [comment]
I was wondering about that — tried googling things like 'webgl random seed' but they kept taking me back to that short function with the hardcoded values.

I've added a `seed` uniform that just replaces one of those hardcoded values, and it seems to work fairly well. No idea if it's the 'correct' solution though!

I also replaced the random function with [this improved version](http://byteblacksmith.com/improvements-to-the-canonical-one-liner-glsl-rand-for-opengl-es-2-0/)

**Comment by Rich-Harris** [comment]
by the way your GitHub bot is awesome

**Comment by gre** [comment]
looks good to me!! thanks :)

**Pull request merged**
