### PR TITLE
FilmBurn

### PR DESCRIPTION
**Pull request by gunrot**

### CODE REVIEW

**Comment by gunrot** [comment]
This seems to be stuck, because something crashed on the server.

**Comment by gunrot** [comment]
Seems to be a reproducable crash.

**Comment by gre** [comment]
weird! have you been able to run `npm test` locally in your branch? seems like there is something in that shader that OpenGL/Linux don't like 🤔

**Comment by gre** [comment]
maybe worth trying to search which part create the problem. maybe could try to inline the `#define` , i've seen weirdness in the past about these

**Pull request merged**
