### PR TITLE
Create Slides.glsl

### PR DESCRIPTION
**Pull request by mrmcsoftware**
Slide out to or in from any corner or edge or center.

### CODE REVIEW

**Review by gltransitions — DISMISSED** [review]
## 👌 All good to me!

- <strong><a href="https://gl-transitions.com/editor?glsl=%2F%2F%20Author%3A%20Mark%20Craig%0A%2F%2F%20mrmcsoftware%20on%20github%20and%20youtube%20(%20http%3A%2F%2Fwww.youtube.com%2FMrMcSoftware%20)%0A%2F%2F%20License%3A%20MIT%0A%0A%2F%2F%20Slides%20Transition%20by%20Mark%20Craig%20(Copyright%20%C2%A9%202022)%0A%0Auniform%20int%20type%3B%20%2F%2F%20%3D%200%0Auniform%20bool%20In%3B%20%2F%2F%20%3D%20false%0A%2F%2F%20type%3A%20slide%20to%2Ffrom%20which%20edge%2C%20which%20corner%2C%20or%20center%0A%2F%2F%20In%3A%20if%20true%20slide%20new%20image%20in%2C%20otherwise%20slide%20old%20image%20out%0A%0A%23define%20rad2%20rad%20%2F%202.0%0A%0Avec4%20transition(vec2%20uv)%0A%7B%0Avec2%20uv0%20%3D%20uv%3B%0Afloat%20rad%20%3D%20In%20%3F%20progress%20%3A%201.0%20-%20progress%3B%0Afloat%20xc1%2C%20yc1%2C%20cx%2C%20cy%3B%0A%2F%2F%20I%20used%20if%2Felse%20instead%20of%20switch%20in%20case%20it's%20an%20old%20GPU%0Aif%20(type%20%3D%3D%200)%20%7B%20cx%20%3D%20.5%3B%20cy%20%3D%200.0%3B%20xc1%20%3D%20.5%20-%20rad2%3B%20yc1%20%3D%200.0%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%201)%20%7B%20cx%20%3D%201.0%3B%20cy%20%3D%20.5%3B%20xc1%20%3D%201.0%20-%20rad%3B%20yc1%20%3D%20.5%20-%20rad2%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%202)%20%7B%20cx%20%3D%20.5%3B%20cy%20%3D%201.0%3B%20xc1%20%3D%20.5%20-%20rad2%3B%20yc1%20%3D%201.0%20-%20rad%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%203)%20%7B%20cx%20%3D%200.0%3B%20cy%20%3D%20.5%3B%20xc1%20%3D%200.0%3B%20yc1%20%3D%20.5%20-%20rad2%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%204)%20%7B%20cx%20%3D%201.0%3B%20cy%20%3D%200.0%3B%20xc1%20%3D%201.0%20-%20rad%3B%20yc1%20%3D%200.0%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%205)%20%7B%20cx%20%3D%20cy%20%3D%201.0%3B%20xc1%20%3D%201.0%20-%20rad%3B%20yc1%20%3D%201.0%20-%20rad%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%206)%20%7B%20cx%20%3D%200.0%3B%20cy%20%3D%201.0%3B%20xc1%20%3D%200.0%3B%20yc1%20%3D%201.0%20-%20rad%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%207)%20%7B%20cx%20%3D%20cy%20%3D%200.0%3B%20xc1%20%3D%200.0%3B%20yc1%20%3D%200.0%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%208)%20%7B%20cx%20%3D%20cy%20%3D%20.5%3B%20xc1%20%3D%20.5%20-%20rad2%3B%20yc1%20%3D%20.5%20-%20rad2%3B%20%7D%0Auv.y%20%3D%201.0%20-%20uv.y%3B%0Avec2%20uv2%3B%0Aif%20((uv.x%20%3E%3D%20xc1)%20%26%26%20(uv.x%20%3C%20xc1%20%2B%20rad)%20%26%26%20(uv.y%20%3E%3D%20yc1)%20%26%26%20(uv.y%20%3C%20yc1%20%2B%20rad))%0A%09%7B%0A%09uv2%20%3D%20vec2((uv.x%20-%20xc1)%20%2F%20rad%2C%201.0%20-%20(uv.y%20-%20yc1)%20%2F%20rad)%3B%0A%09return(In%20%3F%20getToColor(uv2)%20%3A%20getFromColor(uv2))%3B%0A%09%7D%0Areturn(In%20%3F%20getFromColor(uv0)%20%3A%20getToColor(uv0))%3B%0A%7D%0A&name=Slides">✔︎ Slides</a></strong> (compile in 24ms, draw in 25ms)

[](https://i.imgur.com/ymn45IS.gif
)

**Review by gltransitions — APPROVED** [review]
## 👌 All good to me!

- <strong><a href="https://gl-transitions.com/editor?glsl=%2F%2F%20Author%3A%20Mark%20Craig%0A%2F%2F%20mrmcsoftware%20on%20github%20and%20youtube%20(%20http%3A%2F%2Fwww.youtube.com%2FMrMcSoftware%20)%0A%2F%2F%20License%3A%20MIT%0A%0A%2F%2F%20Slides%20Transition%20by%20Mark%20Craig%20(Copyright%20%C2%A9%202022)%0A%0Auniform%20int%20type%3B%20%2F%2F%20%3D%200%0Auniform%20bool%20In%3B%20%2F%2F%20%3D%20false%0A%2F%2F%20type%3A%20slide%20to%2Ffrom%20which%20edge%2C%20which%20corner%2C%20or%20center%0A%2F%2F%20In%3A%20if%20true%20slide%20new%20image%20in%2C%20otherwise%20slide%20old%20image%20out%0A%0A%23define%20rad2%20rad%20%2F%202.0%0A%0Avec4%20transition(vec2%20uv)%0A%7B%0Avec2%20uv0%20%3D%20uv%3B%0Afloat%20rad%20%3D%20In%20%3F%20progress%20%3A%201.0%20-%20progress%3B%0Afloat%20xc1%2C%20yc1%2C%20cx%2C%20cy%3B%0A%2F%2F%20I%20used%20if%2Felse%20instead%20of%20switch%20in%20case%20it's%20an%20old%20GPU%0Aif%20(type%20%3D%3D%200)%20%7B%20cx%20%3D%20.5%3B%20cy%20%3D%200.0%3B%20xc1%20%3D%20.5%20-%20rad2%3B%20yc1%20%3D%200.0%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%201)%20%7B%20cx%20%3D%201.0%3B%20cy%20%3D%20.5%3B%20xc1%20%3D%201.0%20-%20rad%3B%20yc1%20%3D%20.5%20-%20rad2%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%202)%20%7B%20cx%20%3D%20.5%3B%20cy%20%3D%201.0%3B%20xc1%20%3D%20.5%20-%20rad2%3B%20yc1%20%3D%201.0%20-%20rad%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%203)%20%7B%20cx%20%3D%200.0%3B%20cy%20%3D%20.5%3B%20xc1%20%3D%200.0%3B%20yc1%20%3D%20.5%20-%20rad2%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%204)%20%7B%20cx%20%3D%201.0%3B%20cy%20%3D%200.0%3B%20xc1%20%3D%201.0%20-%20rad%3B%20yc1%20%3D%200.0%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%205)%20%7B%20cx%20%3D%20cy%20%3D%201.0%3B%20xc1%20%3D%201.0%20-%20rad%3B%20yc1%20%3D%201.0%20-%20rad%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%206)%20%7B%20cx%20%3D%200.0%3B%20cy%20%3D%201.0%3B%20xc1%20%3D%200.0%3B%20yc1%20%3D%201.0%20-%20rad%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%207)%20%7B%20cx%20%3D%20cy%20%3D%200.0%3B%20xc1%20%3D%200.0%3B%20yc1%20%3D%200.0%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%208)%20%7B%20cx%20%3D%20cy%20%3D%20.5%3B%20xc1%20%3D%20.5%20-%20rad2%3B%20yc1%20%3D%20.5%20-%20rad2%3B%20%7D%0Auv.y%20%3D%201.0%20-%20uv.y%3B%0Avec2%20uv2%3B%0Aif%20((uv.x%20%3E%3D%20xc1)%20%26%26%20(uv.x%20%3C%3D%20xc1%20%2B%20rad)%20%26%26%20(uv.y%20%3E%3D%20yc1)%20%26%26%20(uv.y%20%3C%3D%20yc1%20%2B%20rad))%0A%09%7B%0A%09uv2%20%3D%20vec2((uv.x%20-%20xc1)%20%2F%20rad%2C%201.0%20-%20(uv.y%20-%20yc1)%20%2F%20rad)%3B%0A%09return(In%20%3F%20getToColor(uv2)%20%3A%20getFromColor(uv2))%3B%0A%09%7D%0Areturn(In%20%3F%20getFromColor(uv0)%20%3A%20getToColor(uv0))%3B%0A%7D%0A&name=Slides">✔︎ Slides</a></strong> (compile in 23ms, draw in 26ms)

[](https://i.imgur.com/ybUrP5G.gif
)

**Review by gltransitions — APPROVED** [review]
## 👌 All good to me!

- <strong><a href="https://gl-transitions.com/editor?glsl=%2F%2F%20Author%3A%20Mark%20Craig%0A%2F%2F%20mrmcsoftware%20on%20github%20and%20youtube%20(%20http%3A%2F%2Fwww.youtube.com%2FMrMcSoftware%20)%0A%2F%2F%20License%3A%20MIT%0A%0A%2F%2F%20Slides%20Transition%20by%20Mark%20Craig%20(Copyright%20%C2%A9%202022)%0A%0Auniform%20int%20type%3B%20%2F%2F%20%3D%200%0Auniform%20bool%20In%3B%20%2F%2F%20%3D%20false%0A%2F%2F%20type%3A%20slide%20to%2Ffrom%20which%20edge%2C%20which%20corner%2C%20or%20center%0A%2F%2F%20In%3A%20if%20true%20slide%20new%20image%20in%2C%20otherwise%20slide%20old%20image%20out%0A%0A%23define%20rad2%20rad%20%2F%202.0%0A%0Avec4%20transition(vec2%20uv)%0A%7B%0Avec2%20uv0%20%3D%20uv%3B%0Afloat%20rad%20%3D%20In%20%3F%20progress%20%3A%201.0%20-%20progress%3B%0Afloat%20xc1%2C%20yc1%3B%0A%2F%2F%20I%20used%20if%2Felse%20instead%20of%20switch%20in%20case%20it's%20an%20old%20GPU%0Aif%20(type%20%3D%3D%200)%20%7B%20xc1%20%3D%20.5%20-%20rad2%3B%20yc1%20%3D%200.0%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%201)%20%7B%20xc1%20%3D%201.0%20-%20rad%3B%20yc1%20%3D%20.5%20-%20rad2%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%202)%20%7B%20xc1%20%3D%20.5%20-%20rad2%3B%20yc1%20%3D%201.0%20-%20rad%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%203)%20%7B%20xc1%20%3D%200.0%3B%20yc1%20%3D%20.5%20-%20rad2%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%204)%20%7B%20xc1%20%3D%201.0%20-%20rad%3B%20yc1%20%3D%200.0%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%205)%20%7B%20xc1%20%3D%201.0%20-%20rad%3B%20yc1%20%3D%201.0%20-%20rad%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%206)%20%7B%20xc1%20%3D%200.0%3B%20yc1%20%3D%201.0%20-%20rad%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%207)%20%7B%20xc1%20%3D%200.0%3B%20yc1%20%3D%200.0%3B%20%7D%0Aelse%20if%20(type%20%3D%3D%208)%20%7B%20xc1%20%3D%20.5%20-%20rad2%3B%20yc1%20%3D%20.5%20-%20rad2%3B%20%7D%0Auv.y%20%3D%201.0%20-%20uv.y%3B%0Avec2%20uv2%3B%0Aif%20((uv.x%20%3E%3D%20xc1)%20%26%26%20(uv.x%20%3C%3D%20xc1%20%2B%20rad)%20%26%26%20(uv.y%20%3E%3D%20yc1)%20%26%26%20(uv.y%20%3C%3D%20yc1%20%2B%20rad))%0A%09%7B%0A%09uv2%20%3D%20vec2((uv.x%20-%20xc1)%20%2F%20rad%2C%201.0%20-%20(uv.y%20-%20yc1)%20%2F%20rad)%3B%0A%09return(In%20%3F%20getToColor(uv2)%20%3A%20getFromColor(uv2))%3B%0A%09%7D%0Areturn(In%20%3F%20getFromColor(uv0)%20%3A%20getToColor(uv0))%3B%0A%7D%0A&name=Slides">✔︎ Slides</a></strong> (compile in 21ms, draw in 26ms)

[](https://i.imgur.com/zS6Nt7Y.gif
)

**Comment by gre** [comment]
thanks

**Pull request merged**
