### PR TITLE
Add a mosaic transition

### PR DESCRIPTION
**Pull request by YueDev**

### CODE REVIEW

**Review by gltransitions — APPROVED** [review]
## 👌 All good to me!

- <strong><a href="https://gl-transitions.com/editor?glsl=%2F%2F%20Author%3A%20YueDev%0A%2F%2F%20License%3A%20MIT%0A%0Auniform%20float%20mosaicNum%3B%2F%2F%20%3D%2010.0%0A%0Avec2%20getMosaicUV(vec2%20uv)%20%7B%0A%20%20float%20mosaicWidth%20%3D%202.0%20%2F%20mosaicNum%20*%20min(progress%2C%201.0%20-%20progress)%3B%0A%20%20float%20mX%20%3D%20floor(uv.x%20%2F%20mosaicWidth)%20%2B%200.5%3B%0A%20%20float%20mY%20%3D%20floor(uv.y%20%2F%20mosaicWidth)%20%2B%200.5%3B%0A%20%20return%20vec2(mX%20*%20mosaicWidth%2C%20mY%20*%20mosaicWidth)%3B%0A%7D%0A%0Avec4%20transition%20(vec2%20uv)%20%7B%0A%20%20vec2%20mosaicUV%20%3D%20min(progress%2C%201.0%20-%20progress)%20%3D%3D%200.0%20%3F%20uv%20%3A%20getMosaicUV(uv)%3B%0A%20%20return%20mix(getFromColor(mosaicUV)%2C%20getToColor(mosaicUV)%2C%20progress%20*%20progress)%3B%0A%7D%0A&name=mosaic_transition">✔︎ mosaic_transition</a></strong> (compile in 40ms, draw in 62ms)

[](https://i.imgur.com/YprYZO0.gif
)

**Comment by alifftudm95** [comment]
can someone plz do Hyperzoom transitions? Slow and Fast in/out ease movement with mirror padding around.

**Comment by gre** [comment]
is this shader same as https://github.com/gl-transitions/gl-transitions/blob/master/transitions/Mosaic.glsl ?

**Comment by YueDev** [comment]
> is this shader same as https://github.com/gl-transitions/gl-transitions/blob/master/transitions/Mosaic.glsl ?


There is some differences with Mosaic.glsl

this is Mosaic.glsl：
https://gl-transitions.com/editor?glsl=%2F%2F%20License%3A%20MIT%0A%2F%2F%20Author%3A%20Xaychru%0A%2F%2F%20ported%20by%20gre%20from%20https%3A%2F%2Fgist.github.com%2FXaychru%2F130bb7b7affedbda9df5%0A%0A%23define%20PI%203.14159265358979323%0A%23define%20POW2(X)%20X*X%0A%23define%20POW3(X)%20X*X*X%0Auniform%20int%20endx%3B%20%2F%2F%20%3D%202%0Auniform%20int%20endy%3B%20%2F%2F%20%3D%20-1%0A%0Afloat%20Rand(vec2%20v)%20%7B%0A%20%20return%20fract(sin(dot(v.xy%20%2Cvec2(12.9898%2C78.233)))%20*%2043758.5453)%3B%0A%7D%0Avec2%20Rotate(vec2%20v%2C%20float%20a)%20%7B%0A%20%20mat2%20rm%20%3D%20mat2(cos(a)%2C%20-sin(a)%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sin(a)%2C%20cos(a))%3B%0A%20%20return%20rm*v%3B%0A%7D%0Afloat%20CosInterpolation(float%20x)%20%7B%0A%20%20return%20-cos(x*PI)%2F2.%2B.5%3B%0A%7D%0Avec4%20transition(vec2%20uv)%20%7B%0A%20%20vec2%20p%20%3D%20uv.xy%20%2F%20vec2(1.0).xy%20-%20.5%3B%0A%20%20vec2%20rp%20%3D%20p%3B%0A%20%20float%20rpr%20%3D%20(progress*2.-1.)%3B%0A%20%20float%20z%20%3D%20-(rpr*rpr*2.)%20%2B%203.%3B%0A%20%20float%20az%20%3D%20abs(z)%3B%0A%20%20rp%20*%3D%20az%3B%0A%20%20rp%20%2B%3D%20mix(vec2(.5%2C%20.5)%2C%20vec2(float(endx)%20%2B%20.5%2C%20float(endy)%20%2B%20.5)%2C%20POW2(CosInterpolation(progress)))%3B%0A%20%20vec2%20mrp%20%3D%20mod(rp%2C%201.)%3B%0A%20%20vec2%20crp%20%3D%20rp%3B%0A%20%20bool%20onEnd%20%3D%20int(floor(crp.x))%3D%3Dendx%26%26int(floor(crp.y))%3D%3Dendy%3B%0A%20%20if(!onEnd)%20%7B%0A%20%20%20%20float%20ang%20%3D%20float(int(Rand(floor(crp))*4.))*.5*PI%3B%0A%20%20%20%20mrp%20%3D%20vec2(.5)%20%2B%20Rotate(mrp-vec2(.5)%2C%20ang)%3B%0A%20%20%7D%0A%20%20if(onEnd%20%7C%7C%20Rand(floor(crp))%3E.5)%20%7B%0A%20%20%20%20return%20getToColor(mrp)%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20getFromColor(mrp)%3B%0A%20%20%7D%0A%7D&name=asd

**Pull request merged**
